# Site settings
title: Wöden Kusner
email: wkusner@gmail.com
# description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://wkusner.github.io # the base hostname & protocol for your site
github_username:  githubaccount
twitter_username: twitteraccount

# exclude from generating co-authors
my_authortag: wöden

# collections
collections:
    papers:
        output: true
    posts:
        output: true    

# Build settings
markdown: kramdown
